import pandas as pd
import numpy as np # For np.nan
import io
import joblib
import os
import logging
from django.conf import settings

logger = logging.getLogger(__name__)

# Define model paths relative to the BASE_DIR/models directory
MODEL_DIR = os.path.join(settings.BASE_DIR, 'models')
MODEL_PATHS = {
    'lr': os.path.join(MODEL_DIR, 'pipeline_logistic_regression.pkl'),
    'dt': os.path.join(MODEL_DIR, 'pipeline_decision_tree.pkl'),
    'rf': os.path.join(MODEL_DIR, 'pipeline_random_forest.pkl'),
}

# Expected feature names by the training script (src/train.py)
# These are the column names the pipeline's ColumnTransformer expects.
# We need to ensure the input DataFrame for prediction has these columns.
# Other columns like 'Gender', 'schoolsup', etc. are also in the training
# but not collected by the student form. The pipeline's imputer should handle them.
EXPECTED_INPUT_COLUMNS = [
    'Age', 'Absences', 'Study_Time_per_Week', 'Previous_Grade',
    'Internet_Access', 'Extra_Courses', 'Motivation_Level', 'Parent_Education_Level',
    'Gender', # Not in student form, will be imputed
    'schoolsup', 'famsup', 'activities', 'higher', 'romantic', # Also not in student form
    # Interaction features will be generated
]

# Columns that will be generated by _add_interaction_features_for_prediction
GENERATED_INTERACTION_COLUMNS = [
    'study_high', 'study_med', 'study_low',
    'grade_high', 'grade_med', 'grade_low',
    'abs_int_net',
    'study_parent_pri', 'study_parent_sec', 'study_parent_ter',
    'grade_age'
]

def _map_input_data_to_feature_names(input_data_dict):
    """
    Maps student form data (or similar dict) to the feature names expected by the model.
    Handles type conversion for boolean and choice fields.
    """
    mapping = {
        'age': 'Age',
        'absences': 'Absences',
        'study_time': 'Study_Time_per_Week', # Form field name to training name
        'previous_grade': 'Previous_Grade',
        'internet_access': 'Internet_Access', # Boolean in form, model expects 'Yes'/'No' or 0/1 (pipeline handles this)
        'extra_courses': 'Extra_Courses',     # Boolean in form, model expects 'Yes'/'No' or 0/1
        'motivation_level': 'Motivation_Level', # Choice field (1-5)
        'parent_education': 'Parent_Education_Level' # Choice field (0-7)
    }
    processed_data = {}
    for form_key, model_key in mapping.items():
        value = input_data_dict.get(form_key)
        if value is not None:
            if model_key == 'Internet_Access' or model_key == 'Extra_Courses':
                # Pipeline's OneHotEncoder will handle 'Yes'/'No' or it might expect numeric.
                # Let's convert to string 'Yes'/'No' as that's more common for OHE if not binary encoded prior.
                # The training script's dummy data uses 'Yes'/'No' for these.
                processed_data[model_key] = 'Yes' if value else 'No'
            elif model_key == 'Study_Time_per_Week':
                # Form uses 1,2,3,4. Model might expect actual hours or categories.
                # The dummy data in data_processing.py uses numeric hours (e.g. 1-10).
                # The choices are: (1, '<2 hours/week'), (2, '2-5 hours/week'), (3, '5-10 hours/week'), (4, '>10 hours/week')
                # Let's map to a representative numeric value (e.g., midpoint or lower bound)
                # This needs to align with how 'Study_Time_per_Week' was treated in training.
                # The training's dummy data `np.random.uniform(1, 10, size=100).round(1)` suggests direct hours.
                # For now, let's use a simple mapping. This is a critical point of alignment.
                # The interaction features `study_low/med/high` are based on quantiles of `Study_Time_per_Week`.
                study_time_mapping = {1: 1.5, 2: 3.5, 3: 7.5, 4: 12.0} # Example mapping
                processed_data[model_key] = study_time_mapping.get(int(value), np.nan)
            elif model_key == 'Motivation_Level' or model_key == 'Parent_Education_Level':
                # These are choice fields. The pipeline expects them as categorical features.
                # Convert to string to be safe, as OHE handles strings.
                processed_data[model_key] = str(value)
            else:
                processed_data[model_key] = value
        else:
            processed_data[model_key] = np.nan # Use NaN for missing values, imputer will handle
    return processed_data

def _add_interaction_features_for_prediction(df):
    """
    Adds interaction features to a DataFrame, mirroring src/data_processing.py.
    Handles cases where base columns for interactions might be missing in single student prediction.
    Input df should have columns like 'Study_Time_per_Week', 'Previous_Grade', etc.
    """
    df_out = df.copy()

    # Study_Time_per_Week interactions
    if 'Study_Time_per_Week' in df_out.columns and not df_out['Study_Time_per_Week'].isnull().all():
        # For single prediction, quantiles don't make sense.
        # We must use pre-calculated quantiles from the training set or use fixed thresholds.
        # For now, let's use fixed thresholds based on typical interpretations of the form choices.
        # This is a simplification. Ideally, these thresholds come from training data analysis.
        # study_time form choices: 1 (<2h), 2 (2-5h), 3 (5-10h), 4 (>10h)
        # Mapped values: 1.5, 3.5, 7.5, 12.0
        # Let's define 'low' as <2h, 'med' as 2-5h, 'high' as >5h for this example.
        # This part MUST align with how it was done in train.py's add_interaction_features,
        # which used quantiles. This function will need adjustment if those quantiles are not
        # available here. For now, this is a placeholder logic.
        # A better way: save quantiles from training and load them here.
        # For now, using placeholder logic for single student:
        stw = df_out['Study_Time_per_Week'].iloc[0] if not df_out.empty else np.nan
        df_out['study_low'] = int(stw < 2) if pd.notna(stw) else 0
        df_out['study_med'] = int(2 <= stw < 5) if pd.notna(stw) else 0
        df_out['study_high'] = int(stw >= 5) if pd.notna(stw) else 0
    else:
        df_out['study_low'] = 0
        df_out['study_med'] = 0
        df_out['study_high'] = 0

    # Previous_Grade interactions
    if 'Previous_Grade' in df_out.columns and not df_out['Previous_Grade'].isnull().all():
        # Similar to study time, using fixed thresholds for single prediction.
        # Example: low < 60, med 60-80, high > 80
        pg = df_out['Previous_Grade'].iloc[0] if not df_out.empty else np.nan
        df_out['grade_low'] = int(pg < 60) if pd.notna(pg) else 0
        df_out['grade_med'] = int(60 <= pg < 80) if pd.notna(pg) else 0
        df_out['grade_high'] = int(pg >= 80) if pd.notna(pg) else 0
    else:
        df_out['grade_low'] = 0
        df_out['grade_med'] = 0
        df_out['grade_high'] = 0

    # Absences * Internet_Access
    if 'Absences' in df_out.columns and 'Internet_Access' in df_out.columns:
        # Form gives True/False for internet_access, mapped to 'Yes'/'No'.
        # Model's OHE will handle 'Yes'/'No'. Interaction expects numeric.
        internet_numeric = df_out['Internet_Access'].replace({'Yes': 1, 'No': 0, True: 1, False: 0}).fillna(0)
        df_out['abs_int_net'] = df_out['Absences'].fillna(0) * internet_numeric
    else:
        df_out['abs_int_net'] = 0

    # Study_Time_per_Week * Parent_Education_Level
    # This is complex as Parent_Education_Level is categorical.
    # The training script's add_interaction_features uses placeholders like:
    # df_out['study_parent_pri'] = df_out['Study_Time_per_Week'] * (df_out['Parent_Education_Level'] == 'HighSchool').astype(int)
    # We need to replicate this for specific Parent_Education_Level string values from the form.
    # Form parent_education choices: 0 ('None') to 7 ('Doctorate'). Mapped to string.
    # Example: if form 'parent_education' is 3 (High School), map to '3'.
    # Then check df_out['Parent_Education_Level'] == '3'.
    # This requires knowing the exact string representation the OHE expects or that was used in training for these interactions.
    # For now, let's assume the stringified numbers from choices are used.
    if 'Study_Time_per_Week' in df_out.columns and 'Parent_Education_Level' in df_out.columns:
        stw_val = df_out['Study_Time_per_Week'].fillna(0)
        pel_val = df_out['Parent_Education_Level'] # This should be string e.g. '0', '1', ... '7'
        # Example: interaction with 'Upper Secondary Education (High School Diploma or GED)' which is choice '3'
        df_out['study_parent_pri'] = stw_val * (pel_val == '3').astype(int) # Primary interaction for 'High School'
        df_out['study_parent_sec'] = stw_val * (pel_val == '5').astype(int) # Secondary interaction for 'Bachelor's'
        df_out['study_parent_ter'] = stw_val * (pel_val == '7').astype(int) # Tertiary interaction for 'Doctorate'
    else:
        df_out['study_parent_pri'] = 0
        df_out['study_parent_sec'] = 0
        df_out['study_parent_ter'] = 0

    # Previous_Grade / Age
    if 'Previous_Grade' in df_out.columns and 'Age' in df_out.columns:
        age_val = df_out['Age'].fillna(18) + 1e-6 # Avoid division by zero, fill NA with a default
        df_out['grade_age'] = df_out['Previous_Grade'].fillna(0) / age_val
    else:
        df_out['grade_age'] = 0

    # Ensure all generated columns exist, even if calculations failed (filled with 0)
    for col in GENERATED_INTERACTION_COLUMNS:
        if col not in df_out.columns:
            df_out[col] = 0

    return df_out

def predict_student(student_form_data, model_key):
    """
    Predicts student performance using a trained pipeline.
    - student_form_data: dict from StudentInfoForm.cleaned_data
    - model_key: 'lr', 'dt', or 'rf'
    """
    if model_key not in MODEL_PATHS:
        logger.error(f"Invalid model key: {model_key}")
        return {"error": "Invalid model selected."}

    model_path = MODEL_PATHS[model_key]
    if not os.path.exists(model_path):
        logger.error(f"Model file not found: {model_path}")
        return {"error": f"Model file not found for {model_key}."}

    try:
        pipeline = joblib.load(model_path)
        logger.info(f"Loaded pipeline: {model_path}")

        # 1. Map form data to expected feature names
        mapped_data = _map_input_data_to_feature_names(student_form_data)

        # 2. Create a DataFrame with one row
        # Ensure all EXPECTED_INPUT_COLUMNS are present, fill with NaN if not in mapped_data
        # This is crucial because the pipeline's ColumnTransformer expects all columns it was trained on.
        input_df_dict = {col: [mapped_data.get(col, np.nan)] for col in EXPECTED_INPUT_COLUMNS}

        # Special handling for columns used by interaction features if they are not in EXPECTED_INPUT_COLUMNS
        # but are base features for interactions (e.g. 'Study_Time_per_Week')
        # The current EXPECTED_INPUT_COLUMNS includes the base features from the form.

        input_df = pd.DataFrame.from_dict(input_df_dict)

        # 3. Add interaction features
        input_df_with_interactions = _add_interaction_features_for_prediction(input_df)

        # Log the DataFrame being sent to the model
        logger.debug(f"DataFrame for prediction (student):\n{input_df_with_interactions.to_string()}")

        # 4. Predict probability (class 1, i.e., "passed")
        # predict_proba returns [[prob_class_0, prob_class_1]]
        proba_array = pipeline.predict_proba(input_df_with_interactions)
        probability_passed = proba_array[0, 1]

        # 5. Predict class (0 or 1)
        prediction = pipeline.predict(input_df_with_interactions)[0]
        passed = bool(prediction == 1)

        logger.info(f"Prediction for student using {model_key}: Passed={passed}, Probability={probability_passed:.4f}")
        # Log which pipeline was used and basic stats (n_samples=1)
        # Actual accuracy from training is not directly available here unless stored with the model or logged separately.
        logger.info(f"Pipeline {model_key} used. n_samples=1.")


        return {
            "passed": passed,
            "probability_score": round(float(probability_passed), 3),
            "model_used": model_key,
            "error": None
        }

    except FileNotFoundError:
        logger.exception(f"Model file not found for {model_key} at {model_path}")
        return {"error": f"Model file for {model_key} not found.", "passed": None, "probability_score": None}
    except Exception as e:
        logger.exception(f"Error during student prediction with model {model_key}: {e}")
        return {"error": f"Prediction error: {str(e)}", "passed": None, "probability_score": None}


def batch_predict(file_path_or_buffer, model_key):
    """
    Performs batch prediction on a CSV file using a trained pipeline.
    - file_path_or_buffer: Path to CSV file or file-like object.
    - model_key: 'lr', 'dt', or 'rf'
    """
    if model_key not in MODEL_PATHS:
        logger.error(f"Invalid model key for batch prediction: {model_key}")
        return pd.DataFrame(), "Invalid model selected."

    model_path = MODEL_PATHS[model_key]
    if not os.path.exists(model_path):
        logger.error(f"Model file not found for batch prediction: {model_path}")
        return pd.DataFrame(), f"Model file not found for {model_key}."

    try:
        pipeline = joblib.load(model_path)
        logger.info(f"Loaded pipeline for batch prediction: {model_path}")

        # 1. Load data from CSV
        try:
            if isinstance(file_path_or_buffer, str):
                input_df_original = pd.read_csv(file_path_or_buffer)
            else:
                file_path_or_buffer.seek(0)
                input_df_original = pd.read_csv(io.StringIO(file_path_or_buffer.read().decode('utf-8', errors='replace')))
        except Exception as e:
            logger.exception(f"Error reading CSV for batch prediction: {e}")
            return pd.DataFrame(), f"Error reading CSV: {str(e)}"

        input_df = input_df_original.copy()

        # 2. Map CSV column names to standardized model feature names if necessary.
        # Assuming CSV columns are already named like 'Age', 'Absences', 'Study_Time_per_Week', etc.
        # The form mapping logic in _map_input_data_to_feature_names includes type conversion
        # and renaming. For CSV, we might need a similar step if columns are different.
        # For now, assume CSV columns match the _map_input_data_to_feature_names output keys or
        # directly match the EXPECTED_INPUT_COLUMNS.
        # Example: if CSV has "Student Age", map to "Age".
        # This part is crucial for robustness.
        # Let's try to apply a similar mapping logic for consistency,
        # especially for boolean/categorical representations.

        # Create a list of dictionaries, one for each row
        list_of_dicts = input_df.to_dict(orient='records')
        processed_rows = []
        for row_dict in list_of_dicts:
            # Use a modified mapping or direct mapping if CSV headers are assumed to be correct
            # For now, let's assume we need to map CSV headers if they are like form field names
            # This is a placeholder and needs careful thought based on expected CSV format

            # Renaming columns in the DataFrame to match 'student_form_data' keys for _map_input_data_to_feature_names
            # This is just one way, could also adapt _map_input_data_to_feature_names
            csv_to_form_key_map = {
                'Age': 'age', 'Absences': 'absences', 'Study_Time_per_Week': 'study_time',
                'Previous_Grade': 'previous_grade', 'Internet_Access': 'internet_access',
                'Extra_Courses': 'extra_courses', 'Motivation_Level': 'motivation_level',
                'Parent_Education_Level': 'parent_education'
                # Add other direct mappings or handle columns not in form
            }
            # Create a temporary dict with keys that _map_input_data_to_feature_names expects
            temp_form_like_dict = {}
            for csv_col, value in row_dict.items():
                form_key = csv_to_form_key_map.get(csv_col, csv_col) # keep original name if not in map
                temp_form_like_dict[form_key] = value

            processed_rows.append(_map_input_data_to_feature_names(temp_form_like_dict))

        mapped_df = pd.DataFrame(processed_rows)

        # Ensure all EXPECTED_INPUT_COLUMNS are present
        for col in EXPECTED_INPUT_COLUMNS:
            if col not in mapped_df.columns:
                mapped_df[col] = np.nan

        # Select only expected columns before interactions, in correct order if it matters (it does for some models if not using df directly)
        # However, ColumnTransformer selects by name, so order before preprocessor is less critical than presence.
        df_for_interactions = mapped_df[EXPECTED_INPUT_COLUMNS].copy()


        # 3. Add interaction features
        # The _add_interaction_features_for_prediction was designed for single rows,
        # for batch, the original add_interaction_features from data_processing.py
        # (which uses quantiles) is more appropriate if it can be imported or replicated.
        # For now, we'll use the adapted one, but it might not be ideal for batch if quantiles are important.
        # Re-checking src/data_processing.py, it uses quantiles.
        # This means _add_interaction_features_for_prediction is a simplified version.
        # For batch, we SHOULD use the quantile-based one if possible.
        # Let's assume for now the simplified one is acceptable for this step.
        # TODO: Align interaction feature generation for batch processing with training method.

        # Iteratively apply _add_interaction_features_for_prediction (not efficient for batch)
        # A better way: make _add_interaction_features_for_prediction vectorized or use the original.
        # For now, let's try to make it work row by row, or adapt it.
        # Adapting for batch:
        input_df_with_interactions = _add_interaction_features_for_prediction(df_for_interactions) # This should work if df_for_interactions is a DataFrame

        logger.debug(f"DataFrame for batch prediction (first 5 rows):\n{input_df_with_interactions.head().to_string()}")

        # 4. Predict probabilities and classes
        proba_array = pipeline.predict_proba(input_df_with_interactions)
        predictions = pipeline.predict(input_df_with_interactions)

        # Add predictions to the *original* DataFrame
        input_df_original[f'predicted_passed_{model_key}'] = (predictions == 1)
        input_df_original[f'predicted_probability_{model_key}'] = np.round(proba_array[:, 1], 3)

        logger.info(f"Batch prediction complete using {model_key} for {len(input_df_original)} records.")
        # Log which pipeline was used and basic stats
        logger.info(f"Pipeline {model_key} used for batch. n_samples={len(input_df_original)}.")

        return input_df_original, None

    except FileNotFoundError:
        logger.exception(f"Model file not found for batch {model_key} at {model_path}")
        return pd.DataFrame(), f"Model file for {model_key} not found."
    except Exception as e:
        logger.exception(f"Error during batch prediction with model {model_key}: {e}")
        return pd.DataFrame(), f"Batch prediction error: {str(e)}"
    return df

def get_sample_csv_data():
    """
    Returns a string representing sample CSV data.
    """
    sample_data = {
        'Previous Grade': [75, 88, 60, 92, 78],
        'Absences': [2, 0, 5, 1, 3],
        'Study Time': [10, 15, 8, 20, 12],
        'Age': [17, 18, 17, 19, 18],
        'Internet Access': [True, True, False, True, True],
        'Extra Courses': [False, True, False, True, False],
        'Motivation': [4, 5, 3, 5, 4],
        'Parent Education': [3, 4, 2, 5, 3]
    }
    df = pd.DataFrame(sample_data)
    return df.to_csv(index=False)
